### ISSUE TITLE
Laravel 5.8 Support

### ISSUE THREAD

**Issue by FascistDonut** [ptondereau/Laravel-UPS-Api#17]
Needs to be updated so we can use Laravel 5.8. Thanks.

**Comment by impactcolor** [comment]
@FascistDonut  
I think you mean, can you please update for Laravel 5.8, we would greatly appreciate it.

**Comment by mendicm** [comment]
Solved on GH-16. @ptondereau can you merge it please?

**Comment by sebhegil** [comment]
Hi. Any updates when this package will be available for laravel 5.8? Thanks.

**Comment by kevmul** [comment]
Hello, I would like to use your package but I need support for Laravel 5.8. If you could update for Laravel 5.8, I would greatly appreciate it.

**Comment by ptondereau** [comment]
Sorry for delay, 1.0.12 is now out!

**Comment by kevmul** [comment]
Thank you!
